---
- name: Desktop - Copy wallpaper file
  tags: wallpaper
  become: true
  copy:
    src: files/desktop/wallpaper.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg

- name: Desktop - dconf-editor
  tags: wallpaper
  become: true
  apt:
    name: dconf-editor
    state: present
    update_cache: yes

- name: Desktop - Set wallpaper
  tags: wallpaper
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: Desktop - Set wallpaper - dark mode
  tags: wallpaper
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"
